#!/bin/bash
# SPDX-License-Identifier: GPL-2.0
#
# find_uncompiled_files.sh
#
# Find .c and .h files under a specified directory that did not participate
# in the kernel compilation process. Results are written to an output file
# with paths relative to the kernel source root.
#
# The script works by parsing the .cmd dependency files generated by the
# kernel build system (via fixdep). These files record every source and
# header file involved in each compilation unit.
#
# Prerequisites:
#   - The kernel must have been built (so .cmd files exist)
#   - Run this script from the kernel source tree root
#
# Usage:
#   scripts/find_uncompiled_files.sh -d <directory> [-o <output>] [-B <build_dir>]
#
# Options:
#   -d DIR     Directory to scan, relative to source root (e.g., drivers)
#   -o FILE    Output file (default: uncompiled_files.txt)
#   -B DIR     Build output directory for out-of-tree builds (default: .)
#
# Examples:
#   scripts/find_uncompiled_files.sh -d drivers
#   scripts/find_uncompiled_files.sh -d drivers -o unused_drivers.txt
#   scripts/find_uncompiled_files.sh -d drivers -B /path/to/build/output
#
# Output format (one file per line):
#   drivers/android/dbitmap.h
#   drivers/some/unused_driver.c

set -e

TARGET_DIR=""
OUTPUT_FILE="uncompiled_files.txt"
BUILD_DIR="."

usage() {
	cat <<EOF
Usage: $0 -d <directory> [-o <output_file>] [-B <build_dir>]

Find .c and .h files not participating in kernel compilation.

Options:
  -d DIR     Directory to scan, relative to source root (e.g., drivers)
  -o FILE    Output file (default: uncompiled_files.txt)
  -B DIR     Build output directory for out-of-tree builds (default: .)
  -h         Show this help message

Example:
  $0 -d drivers
  $0 -d drivers -o unused_drivers.txt -B /path/to/build

Output format (one file per line):
  drivers/android/dbitmap.h
  drivers/some/unused_driver.c
EOF
	exit "${1:-1}"
}

while getopts "d:o:B:h" opt; do
	case $opt in
	d)
		TARGET_DIR="$OPTARG"
		;;
	o)
		OUTPUT_FILE="$OPTARG"
		;;
	B)
		BUILD_DIR="$OPTARG"
		;;
	h)
		usage 0
		;;
	*)
		usage 1
		;;
	esac
done

if [ -z "$TARGET_DIR" ]; then
	echo "Error: -d <directory> is required." >&2
	usage 1
fi

# Normalize paths - remove trailing slashes
TARGET_DIR="${TARGET_DIR%/}"
BUILD_DIR="${BUILD_DIR%/}"

if [ ! -d "$TARGET_DIR" ]; then
	echo "Error: '$TARGET_DIR' is not a valid directory." >&2
	exit 1
fi

# Create temporary directory for intermediate files
TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

# Step 1: Find all .c and .h files in the target directory
find "$TARGET_DIR" -type f \( -name '*.c' -o -name '*.h' \) | \
	sort > "$TMP_DIR/all_source.txt"

total=$(wc -l < "$TMP_DIR/all_source.txt")
if [ "$total" -eq 0 ]; then
	echo "No .c or .h files found in '$TARGET_DIR'."
	true > "$OUTPUT_FILE"
	exit 0
fi

# Step 2: Collect all .c and .h file paths referenced during compilation.
#
# The kernel build system generates .cmd files (via fixdep) for each
# compiled object. These files contain dependency lists that record every
# source file and header involved in the compilation:
#
#   source_<target> := <source.c>
#   deps_<target> := \
#     path/to/source.c \
#     path/to/header.h \
#     ...
#
# We extract all .c and .h paths from these files to build the set of
# files that participated in compilation.

if ! find "$BUILD_DIR" -name '.*.cmd' -type f -print -quit 2>/dev/null | grep -q .; then
	echo "Warning: No .cmd files found in '$BUILD_DIR'." >&2
	echo "The kernel must be built first to generate build metadata." >&2
	echo "Listing all .c and .h files as uncompiled." >&2
	cp "$TMP_DIR/all_source.txt" "$OUTPUT_FILE"
	echo ""
	echo "Results written to: $OUTPUT_FILE"
	echo "Total uncompiled files: $total (no build data available)"
	exit 0
fi

echo "Scanning '$TARGET_DIR' for .c and .h files not used in kernel build..."
echo "Build directory: $BUILD_DIR"

# Extract all .c and .h file paths from .cmd files.
# The regex matches file paths ending in .c or .h.
# We strip any leading './' to normalize paths.
find "$BUILD_DIR" -name '.*.cmd' -type f -print0 2>/dev/null | \
	xargs -0 grep -hoE '[a-zA-Z0-9_/.+-]+\.[ch]' 2>/dev/null | \
	sed 's|^\./||' | \
	sort -u > "$TMP_DIR/compiled_files.txt"

# Step 3: Find files present in the source tree but not referenced
# in any .cmd dependency file - these are the uncompiled files.
comm -23 "$TMP_DIR/all_source.txt" "$TMP_DIR/compiled_files.txt" \
	> "$OUTPUT_FILE"

# Print summary
total_uncompiled=$(wc -l < "$OUTPUT_FILE")
total_c=$(grep -c '\.c$' "$TMP_DIR/all_source.txt" || true)
total_h=$(grep -c '\.h$' "$TMP_DIR/all_source.txt" || true)
uncompiled_c=$(grep -c '\.c$' "$OUTPUT_FILE" || true)
uncompiled_h=$(grep -c '\.h$' "$OUTPUT_FILE" || true)

echo ""
echo "Results written to: $OUTPUT_FILE"
echo "Summary:"
echo "  .c files: $uncompiled_c uncompiled out of $total_c total"
echo "  .h files: $uncompiled_h uncompiled out of $total_h total"
echo "  Total uncompiled: $total_uncompiled out of $total total"
